"""Telegram Bot handlers and event subscriber for ICT-ML Signal System.
"""

import os
import re
import logging
import asyncio
from datetime import datetime, timezone
from telegram import Update, ReplyKeyboardRemove, BotCommand, MenuButtonCommands, BotCommandScopeDefault
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    filters,
    CallbackContext
)

from config import (
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
    SYMBOLS,
    TIMEFRAME,
    SCAN_INTERVAL_MINUTES,
    SYMBOL,
    INITIAL_BALANCE,
    DEFAULT_RISK_PCT,
    ML_CONFIDENCE_THRESHOLD,
    USE_WEBHOOK,
    WEBHOOK_URL,
    WEBHOOK_PORT,
    WEBHOOK_LISTEN
)
from strategy.risk import calculate_risk
from strategy.combo_fixed import evaluate_ict_combo_fixed
from data.market_data import fetch_recent_candles
from data.database import get_user_settings_db, save_user_settings_db, get_session, Signal
from ml.features import extract_features
from ml.predict import predict_signal_confidence
from bot.messages import format_signal_alert, format_analysis_result, format_backtest_guide
from events.event_bus import event_bus
from services.chart_ocr import extract_chart_info_from_image
from services.chart_generator import generate_signal_chart

# Cache pending signals
awaiting_price = {}
last_generated_signal = {}

telegram_app = None


def get_user_risk(user_id: int) -> dict:
    """Fetch user risk settings persisted in DB."""
    return get_user_settings_db(user_id)


async def post_init(application) -> None:
    """Register native Telegram Bot command menu and persistent Menu button inside main event loop."""
    commands = [
        BotCommand("start", "🤖 Botni ishga tushirish (Gold, NQ, ES)"),
        BotCommand("status", "⚙️ Gold/NQ/ES skaner holati"),
        BotCommand("chart", "📈 So'nggi ICT signali"),
        BotCommand("backtest", "🧪 Futures Chart va CSV backtest"),
        BotCommand("risk", "🛡 Risk $ va Kontrakt hajmini sozlash"),
        BotCommand("settings", "🔧 Juftlik va AI sozlamalari"),
        BotCommand("help", "❓ Qo'llanma va yordam"),
    ]
    try:
        await application.bot.delete_my_commands(scope=BotCommandScopeDefault())
        await application.bot.set_my_commands(commands, scope=BotCommandScopeDefault())
        await application.bot.set_chat_menu_button(menu_button=MenuButtonCommands())
        logging.info("Telegram Bot Command Menu and Persistent Menu Button successfully set up.")
    except Exception as e:
        logging.error(f"Failed to set bot commands or menu button: {e}")


async def start(update: Update, context: CallbackContext) -> None:
    """Handle /start command – greeting without custom keyboard buttons (uses native Telegram Menu)."""
    user_id = update.effective_user.id
    get_user_risk(user_id)  # Ensure DB record exists

    await update.message.reply_text(
        "👋 Salom! ICT-ML Futures Savdo Signal va Backtest botiga xush kelibsiz.\n\n"
        "Bot NQ (Nasdaq), ES (S&P 500), Gold (GC) bo'yicha 6 ta ICT modeli va 80%+ ishonchli XGBoost AI orqali signallarni aniqlaydi.\n\n"
        "💡 Barcha buyruqlar Telegram chap-pastki burchagidagi **Menyu** tugmasida joylashgan:\n"
        "• /status — Tizim holati va birja ulanishi\n"
        "• /chart — So'nggi ICT signalini ko'rish\n"
        "• /backtest — Chart va CSV backtest rejimi\n"
        "• /risk — Depozit va risk foizini o'rnatish (Prop Firm default: $50,000 / 0.5%)\n"
        "• /settings — Skaner sozlamalarini ko'rish\n"
        "• /help — Qo'llanma va yordam\n\n"
        "📸 Tahlil qilish uchun botga Gold, NQ, ES chart skrinshotini yoki narxini yuborishingiz mumkin!",
        reply_markup=ReplyKeyboardRemove()
    )


def handle_new_signal(signal: dict) -> None:
    """Event subscriber callback when a new signal is generated by scanner."""
    global last_generated_signal
    key = datetime.now(timezone.utc).isoformat()
    awaiting_price[key] = signal
    last_generated_signal = signal
    logging.info(f"Signal added to awaiting_price, key: {key}")

    # Check for live execution trigger if live trading is enabled
    try:
        from engine.live_executor import execute_live_signal
        execute_live_signal(signal)
    except Exception as e:
        logging.error(f"Live order execution error: {e}")

    if telegram_app and TELEGRAM_CHAT_ID:
        alert_text = format_signal_alert(signal)
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                asyncio.run_coroutine_threadsafe(
                    telegram_app.bot.send_message(chat_id=TELEGRAM_CHAT_ID, text=alert_text),
                    loop
                )
        except Exception as e:
            logging.error(f"Failed to send async signal alert: {e}")


event_bus.subscribe("SIGNAL_GENERATED", handle_new_signal)


def detect_symbol_from_text(text: str, price: float = None) -> str:
    """Detect active trading pair (NQ, ES, GC) from text or infer automatically from price level."""
    txt_lower = (text or "").lower()
    if any(k in txt_lower for k in ["gold", "xau", "gc"]):
        return "GC"
    elif any(k in txt_lower for k in ["es", "sp", "s&p"]):
        return "ES"
    elif any(k in txt_lower for k in ["nq", "nasdaq"]):
        return "NQ"

    for sym in SYMBOLS:
        if sym.lower() in txt_lower:
            return sym

    # Intelligent Price Range Asset Auto-Inference:
    if price is not None and price > 0:
        if 1500.0 <= price <= 3800.0:
            return "GC"
        elif 3900.0 <= price <= 9000.0:
            return "ES"
        elif price >= 9000.0:
            return "NQ"

    return SYMBOL


async def price_handler(update: Update, context: CallbackContext) -> None:
    """Handle text message with entry price or chart analysis request."""
    user_id = update.effective_user.id
    risk_cfg = get_user_risk(user_id)

    text = update.message.text.strip().replace(",", ".")

    try:
        price = float(text)
    except ValueError:
        await update.message.reply_text("❗️ Iltimos, to'g'ri raqamli narxni kiriting (masalan: 2650.50 yoki 29128.00).")
        return

    pair_name = detect_symbol_from_text(text, price=price)
    signal = awaiting_price.popitem()[1] if awaiting_price else last_generated_signal

    if not signal or signal.get("pair") != pair_name:
        df = fetch_recent_candles(pair_name, limit=200)
        if df.empty:
            df = fetch_recent_candles(SYMBOL, limit=200)
            if not df.empty:
                pair_name = SYMBOL

        combo_res = evaluate_ict_combo_fixed(
            df=df, market_type='futures',
            require_killzone=False, strict_htf_alignment=True,
            symbol=pair_name, timeframe='15m'
        )
        direction = combo_res.get("direction", "LONG")
        if direction not in ["LONG", "SHORT"]:
            direction = "LONG"
        details = combo_res.get("details", {})
        features = extract_features(df, details)
        confidence = predict_signal_confidence(features, rule_confidence=combo_res.get("confluence_score", 0.5))
        signal = {
            "pair": pair_name,
            "direction": direction,
            "confidence": round(confidence * 100, 1),
            "details": details
        }

    direction = signal.get("direction", "LONG").upper()
    sl, tp1, tp2 = calculate_risk(entry_price=price, direction=direction, df=fetch_recent_candles(pair_name, limit=200))

    analysis_text = format_analysis_result(
        entry_price=price,
        direction=direction,
        sl=sl,
        tp1=tp1,
        tp2=tp2,
        details=signal.get("details", {}),
        confidence=signal.get("confidence", 80.0),
        account_deposit=risk_cfg["deposit"],
        risk_pct=risk_cfg["risk_pct"],
        symbol=signal.get("pair", pair_name)
    )

    await update.message.reply_text(analysis_text)


async def photo_handler(update: Update, context: CallbackContext) -> None:
    """Handle clean chart photo upload with asynchronous thread-offloaded OCR vision text & price extraction."""
    user_id = update.effective_user.id
    risk_cfg = get_user_risk(user_id)

    caption = update.message.caption or ""
    msg_id = update.message.message_id
    temp_photo_path = f"scratch_photo_{msg_id}.jpg"

    status_msg = await update.message.reply_text("📸 Chart rasmi qabul qilindi! Vision OCR va AI tahlili hisoblanmoqda...")

    try:
        photo_file = await update.message.photo[-1].get_file()
        await photo_file.download_to_drive(temp_photo_path)

        ocr_res = await asyncio.to_thread(extract_chart_info_from_image, temp_photo_path)
    except Exception as e:
        logging.error("Photo download/OCR error: %s", e)
        ocr_res = {"symbol": "NQ", "detected_price": None, "raw_text": ""}
    finally:
        if os.path.exists(temp_photo_path):
            try:
                os.remove(temp_photo_path)
            except Exception:
                pass

    # 1. Extract price from caption or OCR text
    extracted_price = None
    numbers = re.findall(r"[-+]?\d*\.\d+|\d+", caption.replace(",", "."))
    if numbers:
        try:
            val = float(numbers[0])
            if val > 10.0:
                extracted_price = val
        except ValueError:
            pass

    if not extracted_price:
        extracted_price = ocr_res.get("detected_price")

    # 2. Determine Symbol from Caption, OCR text, or Price range
    full_text = f"{caption} {ocr_res.get('raw_text', '')}"
    pair_name = detect_symbol_from_text(full_text, price=extracted_price)

    # 3. Double-check price range inference for asset matching (Gold 1500-3800, ES 3900-9000, NQ >= 9000)
    if extracted_price and extracted_price > 0:
        if 1500.0 <= extracted_price <= 3800.0:
            pair_name = "GC"
        elif 3900.0 <= extracted_price <= 9000.0:
            pair_name = "ES"
        elif extracted_price >= 9000.0:
            pair_name = "NQ"

    df = fetch_recent_candles(pair_name, limit=200)
    if df.empty:
        df = fetch_recent_candles(pair_name, limit=200)

    entry_price = extracted_price if extracted_price else (float(df.iloc[-1]["close"]) if not df.empty else 2650.0)

    combo_res = evaluate_ict_combo_fixed(
        df=df, market_type='futures',
        require_killzone=False, strict_htf_alignment=True,
        symbol=pair_name, timeframe='15m'
    )
    direction = combo_res.get("direction", "LONG")
    if direction not in ["LONG", "SHORT"]:
        direction = "LONG"
    details = combo_res.get("details", {})

    features = extract_features(df, details) if not df.empty else {}
    confidence = predict_signal_confidence(features, rule_confidence=combo_res.get("confluence_score", 0.5))

    sl, tp1, tp2 = calculate_risk(entry_price=entry_price, direction=direction, df=df)

    analysis_text = format_analysis_result(
        entry_price=entry_price,
        direction=direction,
        sl=sl,
        tp1=tp1,
        tp2=tp2,
        details=details,
        confidence=round(confidence * 100, 1),
        account_deposit=risk_cfg["deposit"],
        risk_pct=risk_cfg["risk_pct"],
        symbol=pair_name
    )

    await status_msg.edit_text(f"🖼 CHART TAHLIL NATIJASI ({pair_name}):\n\n{analysis_text}")


async def document_handler(update: Update, context: CallbackContext) -> None:
    """Handle CSV historical dataset upload for backtesting."""
    doc = update.message.document
    if not doc.file_name.endswith(('.csv', '.txt')):
        await update.message.reply_text("❗️ Faqat `.csv` yoki `.txt` formatidagi fayllarni yuboring.")
        return

    await update.message.reply_text("📂 Fayl qabul qilindi. Tarixiy shamlarda ICT backtest bajarilmoqda...")

    try:
        file_obj = await context.bot.get_file(doc.file_id)
        file_path = f"scratch_backtest_{doc.file_name}"
        await file_obj.download_to_drive(file_path)

        from ml.train_on_csv import clean_and_load_csv, generate_labeled_dataset
        df_clean = clean_and_load_csv(file_path, TIMEFRAME)
        df_dataset = generate_labeled_dataset(df_clean)

        if df_dataset.empty:
            await update.message.reply_text("⚠️ Fayldan yetarli shamlarni o'qib bo'lmadi.")
            return

        total_signals = len(df_dataset)
        wins = int((df_dataset["target"] == 1).sum())
        winrate = (wins / total_signals) * 100.0 if total_signals > 0 else 0.0

        if os.path.exists(file_path):
            os.remove(file_path)

        report = (
            f"🧪 CSV BACKTEST NATIJASI ({doc.file_name})\n"
            f"- Jami aniqlangan signallar: {total_signals}\n"
            f"- Muvaffaqiyatli (TP1/TP2): {wins}\n"
            f"- Yutuq koeffitsiyenti (Winrate): {winrate:.1f}%\n"
            f"- Tavsiya: Model o'qitilgan `ml_model.json` bilan {int(ML_CONFIDENCE_THRESHOLD*100)}%+ ishonchli signallarga amal qiling."
        )
        await update.message.reply_text(report)

    except Exception as e:
        logging.error(f"Document backtest error: {e}")
        await update.message.reply_text(f"❗️ Faylni qayta ishlashda xatolik: {e}")


async def chart(update: Update, context: CallbackContext) -> None:
    """Handle /chart command – always generates and returns a candlestick chart photo."""
    global last_generated_signal

    target_signal = last_generated_signal

    if not target_signal:
        # Check DB for recent signal
        session = get_session()
        try:
            db_sig = session.query(Signal).order_by(Signal.timestamp.desc()).first()
            if db_sig:
                target_signal = {
                    "pair": db_sig.pair,
                    "direction": db_sig.direction,
                    "confidence": db_sig.confidence,
                    "details": {}
                }
        finally:
            session.close()

    pair_name = target_signal.get("pair", SYMBOL) if target_signal else SYMBOL
    df = fetch_recent_candles(pair_name, limit=60)
    if df.empty:
        df = fetch_recent_candles(SYMBOL, limit=60)
        pair_name = SYMBOL

    if not target_signal:
        combo_res = evaluate_ict_combo_fixed(
            df=df, market_type='futures',
            require_killzone=False, strict_htf_alignment=True,
            symbol=pair_name, timeframe='15m'
        )
        direction = combo_res.get("direction", "LONG")
        if direction not in ["LONG", "SHORT"]:
            direction = "LONG"
        details = combo_res.get("details", {})
        features = extract_features(df, details) if not df.empty else {}
        confidence = predict_signal_confidence(features, rule_confidence=combo_res.get("confluence_score", 0.5))
        target_signal = {
            "pair": pair_name,
            "direction": direction,
            "confidence": round(confidence * 100, 1),
            "details": details
        }

    alert_text = format_signal_alert(target_signal)
    chart_buf = generate_signal_chart(df, target_signal)

    await update.message.reply_photo(
        photo=chart_buf,
        caption=f"📈 ICT CHART TAHLILI ({pair_name}):\n\n{alert_text}",
        parse_mode="Markdown"
    )


async def backtest(update: Update, context: CallbackContext) -> None:
    """Handle /backtest command."""
    guide_text = format_backtest_guide()
    await update.message.reply_text(guide_text)


async def risk_cmd(update: Update, context: CallbackContext) -> None:
    """Handle /risk command to set deposit and risk percentage. Usage: /risk 50000 0.5."""
    user_id = update.effective_user.id
    args = context.args

    if len(args) >= 2:
        try:
            dep = float(args[0])
            r_pct = float(args[1])
            save_user_settings_db(user_id, dep, r_pct)
            await update.message.reply_text(
                f"✅ Risk sozlamalari ma'lumotlar bazasida saqlandi:\n"
                f"- Depozit: ${dep:,.2f}\n"
                f"- Har bir savdoga risk: {r_pct}%\n"
                f"- Maksimal yo'qotish: ${dep * (r_pct / 100.0):,.2f}"
            )
            return
        except ValueError:
            pass

    curr = get_user_risk(user_id)
    await update.message.reply_text(
        f"🛡 HOZIRGI RISK SOZLAMALARI (DB Persisted):\n"
        f"- Depozit: ${curr['deposit']:,.2f}\n"
        f"- Risk foizi: {curr['risk_pct']}%\n"
        f"- Har bir savdoga maks. risk: ${curr['deposit'] * (curr['risk_pct'] / 100.0):,.2f}\n\n"
        f"💡 O'zgartirish uchun buyruq kiritining: `/risk 50000 0.5` (50,000$ depozit, 0.5% risk)",
        parse_mode="Markdown"
    )


async def settings(update: Update, context: CallbackContext) -> None:
    """Handle /settings command."""
    symbols_str = ", ".join(SYMBOLS)
    await update.message.reply_text(
        f"🔧 LOYIHA SOZLAMALARI\n"
        f"- Birja: Binance / Bybit / US Futures (yfinance)\n"
        f"- Skanerlanayotgan juftliklar: {symbols_str}\n"
        f"- Timeframe: {TIMEFRAME}\n"
        f"- Skaner intervali: {SCAN_INTERVAL_MINUTES} minut\n"
        f"- Model chegarasi: {int(ML_CONFIDENCE_THRESHOLD*100)}% confidence\n"
        f"- Bot Rejimi: {'Webhook' if USE_WEBHOOK else 'Polling'}"
    )


async def help_cmd(update: Update, context: CallbackContext) -> None:
    """Handle /help command."""
    help_text = (
        "📖 BUYRUQLAR VA FOYDALANISH QO'LLANMASI\n\n"
        "/start - Botni ishga tushirish\n"
        "/status - Tizim va birja ulanish holati\n"
        "/chart - So'nggi ICT signalini ko'rish\n"
        "/backtest - Chart va CSV backtest rejimi\n"
        "/risk [deposit] [risk_pct] - Depozit va risk foizini o'rnatish (masalan: `/risk 50000 0.5`)\n"
        "/settings - Skaner sozlamalarini ko'rish\n"
        "/help - Ushbu qo'llanma\n\n"
        "💡 Backtest yoki Chart Analiz qilish uchun:\n"
        "Shunchaki Gold (GC), NQ, ES chart skrinshotini (rasm) yoki narxni yozib yuboring!"
    )
    await update.message.reply_text(help_text, parse_mode="Markdown")


async def status(update: Update, context: CallbackContext) -> None:
    """Handle /status command."""
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    status_text = (
        f"⚙️ TIZIM HOLATI\n"
        f"Vaqt: {now_utc}\n"
        f"Skanerlash intervali: {SCAN_INTERVAL_MINUTES} daqiqa\n"
        f"Kuzatuvdagi juftliklar: {', '.join(SYMBOLS)}\n"
        f"Timeframe: {TIMEFRAME}\n"
        f"Kutilayotgan signallar: {len(awaiting_price)}\n"
        f"Rejim: {'Webhook' if USE_WEBHOOK else 'Polling'}\n"
        f"Holat: 🟢 Faol ishlamoqda"
    )
    await update.message.reply_text(status_text)


def start_bot() -> None:
    """Initialize and run Telegram Bot with clean UI and Webhook/Polling switcher."""
    global telegram_app
    if not TELEGRAM_BOT_TOKEN:
        logging.warning("TELEGRAM_BOT_TOKEN missing.")
        return

    telegram_app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).post_init(post_init).build()

    # Register Command Handlers
    telegram_app.add_handler(CommandHandler("start", start))
    telegram_app.add_handler(CommandHandler("status", status))
    telegram_app.add_handler(CommandHandler("chart", chart))
    telegram_app.add_handler(CommandHandler("backtest", backtest))
    telegram_app.add_handler(CommandHandler("risk", risk_cmd))
    telegram_app.add_handler(CommandHandler("settings", settings))
    telegram_app.add_handler(CommandHandler("help", help_cmd))

    # Register Media Handlers
    telegram_app.add_handler(MessageHandler(filters.PHOTO, photo_handler))
    telegram_app.add_handler(MessageHandler(filters.Document.ALL, document_handler))
    telegram_app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, price_handler))

    if USE_WEBHOOK and WEBHOOK_URL:
        logging.info(f"Starting Telegram Bot in WEBHOOK mode on {WEBHOOK_LISTEN}:{WEBHOOK_PORT}...")
        try:
            telegram_app.run_webhook(
                listen=WEBHOOK_LISTEN,
                port=WEBHOOK_PORT,
                url_path=TELEGRAM_BOT_TOKEN,
                webhook_url=f"{WEBHOOK_URL}/{TELEGRAM_BOT_TOKEN}"
            )
        except Exception as e:
            logging.error(f"Webhook execution failed: {e}. Falling back to Polling...")
            telegram_app.run_polling()
    else:
        logging.info("Starting Telegram Bot in POLLING mode...")
        try:
            telegram_app.run_polling()
        except Exception as e:
            logging.error("Telegram bot error: %s", e)
